### ISSUE TITLE
Merge coq-alternate-reals in there

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#1]
The library https://github.com/strub/coq-alternate-reals or its (slight) fork (https://github.com/CohenCyril/coq-alternate-reals) should be merged in there, and the external dependency should be removed.

**Comment by CohenCyril** [comment]
Hi @strub, do you have any idea when you have some time to perform this merge?

**Comment by strub** [comment]
Sometime between Friday and Monday.
