### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#1038]
https://github.com/math-comp/analysis/blob/a5e2c659ea31a86b4789c9094f771d960187bf5c/theories/realfun.v#L14-L15

@CohenCyril I remember that you recently made a comment about this documentation being wrong but I cannot find your comment. What was it?

**Comment by CohenCyril** [comment]
cf
https://github.com/math-comp/analysis/pull/873#discussion_r1296858851
and 
https://github.com/math-comp/analysis/pull/794#discussion_r1038602313
