### ISSUE TITLE
Please create a tag for Coq 8.18 in Coq Platform 2023.10

### ISSUE THREAD

**Issue by rtetley** [math-comp/analysis#1048]
The Coq team released Coq `8.18.0` on September 7th, 2023.
The corresponding Coq Platform release `2023.10` should be released before **November 30th, 2023**.
It can be delayed in case of difficulties until January 15th, 2023, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (0.6.5) **does not work** with Coq `8.18.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI appears to test this project, but has some special handling for your project which makes it difficult to retrieve the commit it tests for your project.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.18, **preferably before October 31st, 2023**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before October 31st, 2023, it will be included in an early Coq Platform beta release of the for Coq 8.18.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.18+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.18+beta1.sh) which already supports Coq version `8.18.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/372

**Comment by rtetley** [comment]
Hey @affeldt-aist ! Doing a round of reminders ! Could you give us a status ?

**Comment by affeldt-aist** [comment]
> This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (0.6.5) does not work with Coq 8.18.0.

I can compile 0.6.5 on my computer with Coq 8.18.0
(with Hierarchy-Builder 1.6.0, MathComp 1.16, finmap 1.5.2).

**Comment by affeldt-aist** [comment]
We have also updated the version of MathComp-Analysis from 0.6.5 to 0.6.6, maybe this has solved the issue.

**Comment by MSoegtropIMC** [comment]
As discussed in Zulip the issue was that we tested with MC 2.x. We will do two separate picks. In the MC 1.18 based pick, we will use mathcomp-analysis 0.6.6.

**Comment by MSoegtropIMC** [comment]
As discussed in Zulip the upcoming release of Coq platform contains two picks, one based on mathcomp 1.18 and one based on mathcomp 2.1. See (https://github.com/math-comp/math-comp/issues/1089).

For mathcomp-analysis we picked:

MC2.1: **not included**
MC1.18: coq-mathcomp-analysis.0.6.6

**If this is what you want, please close this ticket - otherwise please ping us asap.**

**Comment by affeldt-aist** [comment]
This looks ok! Sorry for the trouble...

**Comment by MSoegtropIMC** [comment]
No issue at all - luckily we have the flexibility to provide two separate picks in one release.
