### ISSUE TITLE
Prepare opam package for 0.1.0 and push to the coq opam archive

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#109]

**Comment by spitters** [comment]
The INSTALL.md says this library is already in opam. However, it seems to be missing here:
https://coq.inria.fr/opam/extra-dev/packages/

Do I understand correctly that this issue is trying to solve that?

**Comment by CohenCyril** [comment]
> The INSTALL.md says this library is already in opam. However, it seems to be missing here:
> https://coq.inria.fr/opam/extra-dev/packages/
> 
> Do I understand correctly that this issue is trying to solve that?

Hi @spitters, yes, it was... and I finally had the time to do it.
