### ISSUE TITLE
conflicting notation

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#110]
This notation conflicts with the syntax for intro patterns (as in => [[...][...]]).
(That is why it sits in the middle of the file despite being a Reserved.)

https://github.com/math-comp/analysis/blob/3be18107f54445d7b40a7c734b8e49d489fa54d3/hierarchy.v#L1269

**Comment by CohenCyril** [comment]
Yes this very notation is problematic. #4 is the clean solution for that. (Hence replacing `` `[|•|]`` with `` `|•|``
