### ISSUE TITLE
Release with support with more recent Coq and mathcomp

### ISSUE THREAD

**Issue by SnarkBoojum** [math-comp/analysis#1120]
I'm trying to upgrade the Coq packages in Debian using Coq 8.18 and MC2, and this is one of the blockers.

Thanks!

**Comment by proux01** [comment]
A release of analysis for MC2 is expected in January 2024. Meanwhile, all releases of analysis require MC1 (as documented in the opam repo).

**Comment by SnarkBoojum** [comment]
I know but an explicit ticket is better ; notice coq 8.19 is around the corner too...

**Comment by proux01** [comment]
Yes and 8.19 will require releases of mathcomp anyway.

**Comment by affeldt-aist** [comment]
@SnarkBoojum In January, we have released MathComp-Analysis 0.7.0, which is compatible with MathComp 1,
and MathComp-Analysis 1.0.0, which is compatible with MathComp 2. Both are compatible with Coq 8.19.
Does this solve this issue?

**Comment by SnarkBoojum** [comment]
Yes, it does, and I didn't notice this trailing issue. Thanks!
