### ISSUE TITLE
`distribution` in probability.v is inconsistent with its documentation

### ISSUE THREAD

**Issue by t6s** [math-comp/analysis#1185]
https://github.com/math-comp/analysis/blob/95daf6f73fd773414be3a0878aa0ba0aa6989231/theories/probability.v#L20
https://github.com/math-comp/analysis/blob/95daf6f73fd773414be3a0878aa0ba0aa6989231/theories/probability.v#L70

The header documentation says `distribution` takes only one argument `X : {RV P >-> R}`, but its actual definition requires
two arguments `P : probability T R` and `X : {mfun T >-> R}`.

**Comment by affeldt-aist** [comment]
Thanks for reporting!
