### ISSUE TITLE
Instantiate the hierarchy on row vectors

### ISSUE THREAD

**Issue by drouhling** [math-comp/analysis#12]
This work was done for Coquelicot's hierarchy in https://github.com/drouhling/LaSalle/blob/master/vect.v and should be adapted to the new hierarchy to remove the `Admitted` in https://github.com/math-comp/analysis/blob/e2d3d4c57f3c0797d06891669c336ba587eb2ae5/derive.v#L174

Maybe move the instantiations to the corresponding sections in `hierarchy.v`?

**Comment by affeldt-aist** [comment]
> Maybe move the instantiations to the corresponding sections in hierarchy.v?
Yes, definitely.
