### ISSUE TITLE
`inf_lb` should be `inf_lbound`?

### ISSUE THREAD

**Issue by IshiguroYoshihiro** [math-comp/analysis#1258]
Should `inf_lb` be `inf_lbound`?
When I want to prove a goal that `S x -> inf S <= x`, I couldn't find `inf_lb` by searching with `(inf _ <= _)` or `inf "le"`.

https://github.com/math-comp/analysis/blob/59fb6d2c2fa4613bf3bfb3e8dd9c13c9638d727e/theories/reals.v#L398
https://github.com/math-comp/analysis/blob/59fb6d2c2fa4613bf3bfb3e8dd9c13c9638d727e/classical/classical_sets.v#L2908

**Comment by affeldt-aist** [comment]
I agree with the proposed renaming.

**Comment by affeldt-aist** [comment]
The search problem looks to me like a limitation of the `Search` that does not do any unfolding.  Maybe there is a plan to address that. @proux01 ? @CohenCyril ?

**Comment by proux01** [comment]
Well, plans, there definitely are, for years. About effective actions, nothing on my side.
