### ISSUE TITLE
Quotients without ChoiceType?

### ISSUE THREAD

**Issue by spitters** [math-comp/analysis#133]
Is my understanding correct that @CohenCyril constructs quotients over ChoiceType to be able to work with Leibniz equality in a constructive context? 

When using classical logic, this does not seem necessary, as the usual construction we considers elements of the quotient as equivalence classes. With classical logic these are maps A->2, by functional extensionality, these have the right equality.

Am I overlooking something?
This construction would avoid requiring ChoiceTypes in a number of places.

**Comment by CohenCyril** [comment]
Hi @spitters sorry I missed your question a while ago... The library provides a generic `choiceType` for every time for backward compatilibity with core (constructive/axiom-free) mathcomp, hence the absence of special case for quotients.

**Comment by spitters** [comment]
Did you mean to write every Type instead of every time ?

**Comment by CohenCyril** [comment]
> Did you mean to write every Type instead of every time ?

fixed

**Comment by CohenCyril** [comment]
> Hi @spitters sorry I missed your question a while ago... The library provides a generic `choiceType` for every type for backward compatilibity with core (constructive/axiom-free) mathcomp, hence the absence of special case for quotients.

PS: note that this generic `choiceType` is still "on demand" to avoid problems linked to forgetful inheritance.

**Comment by spitters** [comment]
Thanks. Makes more sense now.
