### ISSUE TITLE
broken in coq ci

### ISSUE THREAD

**Issue by SkySkimmer** [math-comp/analysis#1394]
https://gitlab.inria.fr/coq/coq/-/jobs/4948086

**Comment by affeldt-aist** [comment]
It looks like the problem is coming from MathComp.
In the new file `sesquilinear.v` we can observe the following:
```coq
Lemma test (n m : nat) : False.
Proof.
have [_|_] := leqP n m.
Abort.
Reserved Notation "A _|_ B" (at level 69, format "A  _|_  B").
Lemma test (n m : nat) : False.
Proof.
have [_|_] := leqP n m.
(* Error: Syntax error: [hat] or [ssriorpat] expected after '[' (in [ssrcpat]). *)
```
which I find a bit surprising as a user. @proux01

**Comment by affeldt-aist** [comment]
Hopefully this https://github.com/math-comp/math-comp/pull/1291 will fix it.
