### ISSUE TITLE
two files named `path.v` 

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#1412]
We should have noticed that earlier but there are now
two `path.v` files (in `homotopy_theory` and in `ssreflect`)
that cause a conflict when doing `From mathcomp Require Import`.
We may want to rename the one in MathComp-Analysis...

**Comment by affeldt-aist** [comment]
What about `homotopy_path.v` ? @zstone1

**Comment by zstone1** [comment]
Or 'continuous_path' . I'm fine with either.
