### ISSUE TITLE
Why  `lim_cst`?

### ISSUE THREAD

**Issue by amahboubi** [math-comp/analysis#155]
Why is [this](https://github.com/math-comp/analysis/blob/b289c4fe3faf1ced733bd3d0337b2a76d57c7991/theories/normedtype.v#L1087) lemma named 'lim_cst' ? It is a very generic name for such a specialisation to normed modules and functions with **same** domain and codomain. Because of its name, it is easier found than the more often useful [one](https://github.com/math-comp/analysis/blob/b289c4fe3faf1ced733bd3d0337b2a76d57c7991/theories/topology.v#L1472) 'cst_continuous'.

**Comment by affeldt-aist** [comment]
c1a111bdb0135ed94953aa700407c7d9347ef70c
renamed `lim_cst` to `cvg_const`
and in master its type has been generalized.

there is now PR #198 that proposes to use only one lemma (there were actually 3 similar-looking lemmas)
