### ISSUE TITLE
Canonical structures on a given type

### ISSUE THREAD

**Issue by mkerjean** [math-comp/analysis#165]
How could we construct a tool which would unveil all the canonical structures on a given type at some point in a Coq file ? Could the hierarchy builder tool help ?(https://github.com/math-comp/hierarchy-builder) Could we build automatically a graph of the canonical declarations of structures and their dependencies ?
 
This seems crucial when using mathcomp analysis libraries, where one uses regularly the basic properties of a type endowed with much richer structure.

**Comment by CohenCyril** [comment]
`Print Canonical Projections` and grep the type you want to inspect.

**Comment by mkerjean** [comment]
I was thinking of a more graphical user-friendly tool, accounting for the dependencies between structures. Will that be easier with hierarchy builder ?

**Comment by CohenCyril** [comment]
> I was thinking of a more graphical user-friendly tool, accounting for the dependencies between structures. Will that be easier with hierarchy builder ?

Unfortunately the only existing tool is `etc/utils/hierarchy.ml` in core math-comp repo (written by @pi8027) and it generates an inheritance graph between structures, and not the canonical structures on a ground type. I guess it would not be too hard to extend it to get both and by thr way check that no intermediate structure was skipped. On the other hand hierarchy-builder is now solely a generation tool and we did not intend to use it to siaplay anything, but it could also be done at some point (when it is more complete).
@pi8027 what is your opinion?

**Comment by pi8027** [comment]
I have an idea to improve `Print Canonical Projections`, but it may not be so user-friendly as @mkerjean said. In coq/coq#10747, I extended `Print Canonical Projections` to take a constant then print only unification hints synthesized from that constant rather than letting users do grep; however, this improvement in the current form does not apply to this issue. Actually, there are several searching patterns we do with `Print Canonical Projections`:
- find unification hints from a given record projection (or a record),
- find unification hints from a given pattern (this issue),
- find unification hints from a given constant (coq/coq#10747).

Also, record projections (the first case) may occur as patterns (the second case) particularly when we implement join.

**Comment by ejgallego** [comment]
IMVHO this should be a core facility of Coq's Canonical support; indeed it would be great to finish coq/coq#10747 and continue from there.

**Comment by pi8027** [comment]
Also, `[...Type of ...]` notations can be useful to check the availability of a specific instance. For example:
```coq
From mathcomp Require Import all_ssreflect all_algebra.
Check [ringType of _ * _].
```
Output:
```coq
[ringType of ?t * ?t0]
     : ringType
where
?t : [ |- ringType]
?t0 : [ |- ringType]
```
Here we see that `T * T'` has the canonical `ringType` instance if both `T` and `T'` are `ringType`.

**Comment by pi8027** [comment]
With coq/coq#10747, now I can tell Coq to list the canonical instances on a given type:
```coq
Print Canonical Projections sum.
```

```coq
sum <- Countable.sort ( sum_countType )
sum <- Choice.sort ( sum_choiceType )
sum <- Equality.sort ( sum_eqType )
sum <- Finite.sort ( sum_finType )
```

```coq
Print Canonical Projections prod.
```

```coq
prod <- GRing.Ring.sort ( pair_ringType )
prod <- GRing.UnitRing.sort ( pair_unitRingType )
prod <- GRing.Lalgebra.sort ( pair_lalgType )
prod <- GRing.UnitAlgebra.sort ( pair_unitAlgType )
prod <- GRing.Lmodule.sort ( pair_lmodType )
prod <- GRing.Zmodule.sort ( pair_zmodType )
prod <- Countable.sort ( prod_countType )
prod <- GRing.ComUnitRing.sort ( pair_comUnitRingType )
prod <- GRing.ComRing.sort ( pair_comRingType )
prod <- Choice.sort ( prod_choiceType )
prod <- GRing.Algebra.sort ( pair_algType )
prod <- Vector.sort ( pair_vectType )
prod <- Equality.sort ( prod_eqType )
prod <- FinGroup.sort ( extprod_baseFinGroupType )
prod <- Finite.sort ( prod_finType )
```

```coq
Print Canonical Projections Num.NumDomain.sort.
```

```coq
Algebraics.Implementation.type <- Num.NumDomain.sort ( algCnum )
rat <- Num.NumDomain.sort ( rat_numDomainType )
int <- Num.NumDomain.sort ( int_numDomainType )
Num.RealClosedField.sort <- Num.NumDomain.sort ( Num.RealClosedField.numDomainType )
Num.ArchimedeanField.sort <- Num.NumDomain.sort ( Num.ArchimedeanField.numDomainType )
Num.RealField.sort <- Num.NumDomain.sort ( Num.RealField.numDomainType )
Num.RealDomain.sort <- Num.NumDomain.sort ( Num.RealDomain.numDomainType )
Num.ClosedField.sort <- Num.NumDomain.sort ( Num.ClosedField.numDomainType )
Num.NumField.sort <- Num.NumDomain.sort ( Num.NumField.numDomainType )
Num.NumDomain.sort <- GRing.Ring.sort ( Num.NumDomain.ringType )
Num.NumDomain.sort <- GRing.Field.sort ( Num.NumField.numDomain_fieldType )
Num.NumDomain.sort <- GRing.UnitRing.sort ( Num.NumDomain.unitRingType )
Num.NumDomain.sort <- GRing.DecidableField.sort ( Num.ClosedField.numDomain_decFieldType )
Num.NumDomain.sort <- GRing.Zmodule.sort ( Num.NumDomain.zmodType )
Num.NumDomain.sort <- GRing.ComUnitRing.sort ( Num.NumDomain.comUnitRingType )
Num.NumDomain.sort <- GRing.ComRing.sort ( Num.NumDomain.comRingType )
Num.NumDomain.sort <- GRing.IntegralDomain.sort ( Num.NumDomain.idomainType )
Num.NumDomain.sort <- Order.DistrLattice.sort ( Num.RealDomain.numDomain_distrLatticeType )
Num.NumDomain.sort <- Choice.sort ( Num.NumDomain.choiceType )
Num.NumDomain.sort <- Order.POrder.sort ( Num.NumDomain.porderType )
Num.NumDomain.sort <- Order.Total.sort ( Num.RealDomain.numDomain_orderType )
Num.NumDomain.sort <- Equality.sort ( Num.NumDomain.eqType )
Num.NumDomain.sort <- GRing.ClosedField.sort ( Num.ClosedField.numDomain_closedFieldType )
Num.NumDomain.sort <- Num.NormedZmodule.sort ( Num.NormedZmodule.numDomain_normedZmodType )
```

**Comment by mkerjean** [comment]
Great ! Have you tried it on analysis ? I will try it.

**Comment by pi8027** [comment]
@mkerjean @CohenCyril Since `Print Canonical Projections` has been extended with search functionality (this will be a new feature of 8.12), can we close this issue? Or, if it is still unsatisfactory, I suggest moving this issue to the math-comp repository.

**Comment by CohenCyril** [comment]
I'm fine with closing this issue. @mkerjean WDYT?

**Comment by mkerjean** [comment]
I'm fine with closing it. Thanks for your work !
