### ISSUE TITLE
Reserve Notations first

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#23]
Factor out format and levels in new notations using `Reserved Notations`

**Comment by affeldt-aist** [comment]
I factored out a few in landau.v, see bigOmega branch.

**Comment by affeldt-aist** [comment]
It seems that they aren't much left, found two in branch issue23.

**Comment by drouhling** [comment]
There are also all the set notations in `classical_sets.v` and the filter and near notations in `topology.v`.
