### ISSUE TITLE
Find a better name for this.

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#24]
https://github.com/math-comp/analysis/blob/3404704fa195f16d5035d8d87806e155dc6d5581/set.v#L309

**Comment by CohenCyril** [comment]
`at_most_one` might be too verbose

**Comment by drouhling** [comment]
What about `is_set1`?

**Comment by CohenCyril** [comment]
Except it's 0 or 1 element.

**Comment by drouhling** [comment]
Indeed… Maybe add a `sub` somewhere? `is_subset1`?
