### ISSUE TITLE
Set up a continuous integration

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#27]
- Travis?
- ci/circleci?
- other?

**Comment by strub** [comment]
Well, Travis has the benefit to be directly integrated into github.

Le mer. 7 févr. 2018 à 19:34, Cyril Cohen <notifications@github.com> a
écrit :

**Comment by CohenCyril** [comment]
and we are lucky not to rely on more than algebra/field in mathcomp, so we should be within the frustrating limit of 50min...

**Comment by CohenCyril** [comment]
@strub do you mind setting this up?

**Comment by strub** [comment]
Ok.

Le mer. 7 févr. 2018 à 19:38, Cyril Cohen <notifications@github.com> a
écrit :

**Comment by ejgallego** [comment]
For longer builds you want to have a look at what we've done with Circle CI in Coq, in fact once we clean up the scripts I was planning to push it to math-comp. Integration with GH is good.

**Comment by strub** [comment]
Ok, i’ll have a look.

**Comment by CohenCyril** [comment]
@ejgallego is it as easy to set up as travis?

**Comment by CohenCyril** [comment]
@strub Thanks

**Comment by ejgallego** [comment]
> @ejgallego is it as easy to set up as travis?

A bit harder, but can reuse build products from previous stages. So it is possible to build first math-comp and then Feit-Thompson reusing the library from the first build. This is how it looks in Coq now:

https://circleci.com/workflow-run/f304bb71-af15-4df1-a8a9-5d412d0d8d2a

[you'll need an account]

The main downside of Circle is that you have 4 workers _for all contributors_ while in Travis you get 5 for each; I don't think that would be a problem for MC.

**Comment by strub** [comment]
If you want me to play with Circle CI, some admin. of mathcomp should adhere to a Circle CI plan.

**Comment by CohenCyril** [comment]
> If you want me to play with Circle CI, some admin. of mathcomp should adhere to a Circle CI plan.

@strub done

**Comment by strub** [comment]
@ejgallego How many containers the Coq project is having?!

**Comment by ejgallego** [comment]
@strub 4 . The container language is a bit cryptic as it displays as "1" then "3 for OSS projects" Note that documentation is confusing wrt version 1 vs version 2 [you should use v2].

Also, scheduling is a bit confusing at first due to dependencies.

**Comment by ejgallego** [comment]
Let me know if I can be of help or do you want me to look somewhere.

**Comment by strub** [comment]
M’y question was more : how much time you need per month for Coq. The 1500
minute limit seems a bit low for a project like Coq.

**Comment by ejgallego** [comment]
> M’y question was more : how much time you need per month for Coq. The 1500
> minute limit seems a bit low for a project like Coq.

This limit doesn't apply to open source projects as far as we can tell.

**Comment by strub** [comment]
For me, this is unclear. It seems that they are starting to enforce the limit.

**Comment by ejgallego** [comment]
I think we discussed that in the Coq channel and the conclusion was that the limit doesn't apply to open source projects, but my memory is not the best maybe @maximedenes @Zimmi48 or @SkySkimmer may remember better.

As far as I can tell, the limit hasn't been enforced in the Coq CI. Note that scheduling of Circle is a bit counterintuitive if you are coming from Travis.

**Comment by SkySkimmer** [comment]
1500min go by pretty fast for Coq, I think we would have noticed.
There was a time I thought we had only 3 jobs and wondered if the 1 (in
>The container language is a bit cryptic as it displays as "1" then "3 for OSS projects"

) was out of minutes with the other 3 being unlimited but I never figured out if that was true or just some scheduling artifact with the 4th job not being started where I watched (or some other unrelated thing, who knows).

**Comment by SkySkimmer** [comment]
For instance https://circleci.com/gh/organizations/SkySkimmer/settings
![screenshot: >250hours/month used](https://screenshotscdn.firefoxusercontent.com/images/76852a43-8b17-4460-8201-5979c93f2340.png)

**Comment by strub** [comment]
Ok, so I did some research. The pricing plan says nothing about time limits and OSS projects (only that OSS projects get 3 more free containers). Up to October'17, they were not enforcing any time limit (they were only shutting down "abusers"). Starting from October'17, they started to gradually enforce the time limit on private projects. But I wouldn't be surprised that, in 1 or 2 years, they start to enforce it on all projects, the pricing plans being quite clear about the limits.

Anyway, "tant que je gagne, je joue", so I'm currently fine with the current status quo.

**Comment by ejgallego** [comment]
I agree that the status with CircleCI is clear, but until we don't have a more powerful gitlab + AWS spot instances setup, Circle seems like the easiest way to do a long chain of builds.

I wonder what's missing for Gitlab thou, @SkySkimmer , isn't it the case than gitlab can reuse artifacts from previous builds?

**Comment by SkySkimmer** [comment]
>I wonder what's missing for Gitlab thou, @SkySkimmer , isn't it the case than gitlab can reuse artifacts from previous builds?

It can.

**Comment by ejgallego** [comment]
Thanks. Yeah so hopefully we can setup a bot someday to push to gitlab and have the testing done there.

**Comment by ejgallego** [comment]
As I mentioned on gitter I could provide a 32core runner for math-comp/coq if needed.

**Comment by ejgallego** [comment]
@Zimmi48 I don't think that's a hijack at all, I would expect Coq libraries such as mathcomp to use the same system we use in Coq's CI in the medium term.
