### ISSUE TITLE
Bounded and landau notations

### ISSUE THREAD

**Issue by mkerjean** [math-comp/analysis#271]
After PR[#267](https://github.com/math-comp/analysis/pull/267) is merged, should we add to `landau.v` lemmas about bounded functions using landau notations ? [This](https://github.com/math-comp/analysis/blob/309f5131169a15542e29d9e55a0ee23a2bb67862/theories/banachsteinhaus.v#L219) is needed for Banach-Steinhauss for example. 

NB(rei): PR #267 has been closed but its contents made their was through another PR

**Comment by affeldt-aist** [comment]
Update: Note that PR #267 has been closed and split into PR #283 (now merged) and PR #183 (to be merged shortly)

**Comment by affeldt-aist** [comment]
I am right to think that this issue has not yet been addressed?

**Comment by affeldt-aist** [comment]
Note that the lemma `bounded_landau` mentioned in the first conversation item has made its way to master along with PR #334 . Maybe this issue can be closed now?

**Comment by mkerjean** [comment]
> Note that the lemma `bounded_landau` mentioned in the first conversation item has made its way to master along with PR #334 . Maybe this issue can be closed now?

Yes, happy to close this issue.
