### ISSUE TITLE
Merge Rbar and ereal

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#3]
Merge this with with ereal when issue #1 is solved
https://github.com/math-comp/analysis/blob/1566e324cd4b56d09a1660521d1c31c3e2ec83da/Rbar.v#L42

**Comment by strub** [comment]
What has to be done on that side? Backporting Rbar to ereal and making use of ereal everywhere else?

**Comment by CohenCyril** [comment]
Yes.
NB: Rbar is not used much except for generalizing some statements. We had a discussion with @amahboubi about whether Rbar arithmetic should be used at all: it does not simplify theorems about limits as R^+ \cup {+\infty} does for positive sums.

**Comment by strub** [comment]
Ok. I'll move this part to the main repo. and then we can decide to prune some arithmetic.

**Comment by affeldt-aist** [comment]
FYI, as of today, `Rbar.v` can be removed (from the to-be-merged PR #175) without preventing compilation.
