### ISSUE TITLE
`bounded_on` -> `bounded_near`

### ISSUE THREAD

**Issue by mkerjean** [math-comp/analysis#325]
In `normedtype.v`, `bounded_on f F` means f is bounded on at least one element on the filter `F`. Renaming it by `bounded_near` would be closer to its semantics, and allow the use of `bounded_on f B` for functions bounded on a bornology B (e.g.: simply bounded, uniformly bounded, ...) . 

If legitimate, should this renaming be performed in PR [183](https://github.com/math-comp/analysis/pull/183) or in a new PR ?

**Comment by CohenCyril** [comment]
Makes sense! Please proceed!

**Comment by mkerjean** [comment]
> Makes sense! Please proceed!

In a new PR or in PR 183 ?

**Comment by CohenCyril** [comment]
Whatever is more practical for you!

**Comment by affeldt-aist** [comment]
Fixed by PR #327
