### ISSUE TITLE
Document equiv.

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#33]
https://github.com/math-comp/analysis/blob/abb66fa649a4c6ee061a211c4c834242418d325c/equiv.v#L1

Also, merge with Landau ?

**Comment by affeldt-aist** [comment]
I agree with merge.

**Comment by affeldt-aist** [comment]
What was equiv.v is now documented in landau.v.
I also completed the documentation in landau.v about tentative big-Omega/Theta notations
(see bigOmega branch).

**Comment by drouhling** [comment]
This is resolved by #58
