### ISSUE TITLE
Do we really want the {ereal R} notation?

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#348]
https://github.com/math-comp/analysis/blob/0c0d7b8c949fcbd1c41429fdf1225bc01bedde4f/theories/ereal.v#L80

or should we get along with `er R`?

**Comment by CohenCyril** [comment]
Neither, there should be no brackets (no CS inference) and the name us not well chosen. It should be something like `ext` (as in https://github.com/math-comp/real-closed/blob/table/theories/table.v)

**Comment by affeldt-aist** [comment]
so `ereal R` without curly brackets?

**Comment by CohenCyril** [comment]
so `ext R` or `extended R` or `bar R`

**Comment by affeldt-aist** [comment]
for the sake of discussion (because `ext` looks a bit short and very generic while `extended` is a bit long): `eline R` for extended real line?

**Comment by affeldt-aist** [comment]
fixed by PR #367
