### ISSUE TITLE
uninteresting lemma?

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#382]
https://github.com/math-comp/analysis/blob/8a8036faa787171d9c4773934fc2b9d1d5cf3b13/theories/nngnum.v#L179-L182

during the 2021-05-27 meeting it was said to backport it to MathComp
but since it can be proven as
```
under eq_filter do rewrite andbC.
by rewrite filter_predI.
```
I wonder whether we should not jut get rid of it.

**Comment by CohenCyril** [comment]
I see... yes let's remove it.

**Comment by affeldt-aist** [comment]
This will be taken care of by PR #180
