### ISSUE TITLE
Prepare a opam dev package

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#40]

**Comment by strub** [comment]
I simply created an opam package description file s.t. I can more easily work with my local projects depending on that one.

I don't know what you had in mind.

**Comment by CohenCyril** [comment]
I had what you did in mind, and adding an entry in opam-coq-archive as well

**Comment by CohenCyril** [comment]
done (https://github.com/coq/opam-coq-archive/pull/276)
