### ISSUE TITLE
bigsetU naming

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#400]
There are several lemmas dealing with `\big[setU/set0]` (e.g., `subset_bigsetU` in `classical_sets.v` or `bigsetU_measurable` in `measure.v`) but `bigsetU` is also the name of the identifier behind the `\bigcup_` notation which does not use `setU` explicitly. What about renaming `bigsetU` to `bigcup` and `bigsetI` to `bigcap`?

(by the way, `bigUB_of` in `measure.v` and `trivIset_bigUI` in `classical_sets.v` should maybe be renamed)

**Comment by CohenCyril** [comment]
Yes
