### ISSUE TITLE
Inclusion in the Coq Platform

### ISSUE THREAD

**Issue by MSoegtropIMC** [math-comp/analysis#437]
Dear math-comp Team,

@palmskog requested here: (https://github.com/coq/platform/issues/21) to include your development into the Coq Platform, which is the standard user facing distribution of Coq.

Coq Platform has a "full" and "extended" level. Inclusion in the "full" level requires an explicit statement by the maintainers, that they agree to the [charter](https://github.com/coq/platform/blob/2021.02/charter.md) of the Coq Platform and intend to publish compatible releases for each release of Coq in a reasonable time frame. For the "extended" level the rules are more relaxed. For developments in the "full" level, users should be able to rely on that the package is maintained, so that they can base their own development on it without a large risk that they have to factor it out again later cause of maintenance issues.

Can you please comment in the Coq Platform issue mentioned above if you do want your package included in the Coq Platform in agreement to the Coq Platform [charter](https://github.com/coq/platform/blob/2021.02/charter.md), and if so which level you would prefer?

Best regards,

Michael

**Comment by MSoegtropIMC** [comment]
P.S.: I just saw that the opam package has a 0.X version number, which suggests it should go into the extended level.

**Comment by MSoegtropIMC** [comment]
P.P.S.: can you suggest an example file using this package for the Coq Platform "smoke test kit"?

**Comment by CohenCyril** [comment]
We do not have a "smoke test kit" file for now. When do you need it?

**Comment by MSoegtropIMC** [comment]
> We do not have a "smoke test kit" file for now. When do you need it?

For the time being any file which is in your source tree and compiles iff the analysis package is installed would do. Typically math-comp components have proper module qualification, so I guess any quick compiling file in your source tree would do. For some math-comp components I simply use the "main include file", say "finmap.v" or "all_character.v", which is usually a reasonable check that the files of the package are where they should be.

We can later have something more fancy.

**Comment by MSoegtropIMC** [comment]
Closing this (reviewing old issues).
