### ISSUE TITLE
cvg_seq_bounded

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#439]
https://github.com/math-comp/analysis/blob/92a7e98255032717faab48882960f0b4c2b30e34/theories/normedtype.v#L2740

shouldn't it be `is_cvg_seq_bounded`?

**Comment by CohenCyril** [comment]
Indeed `is_cvg` is the naming convention for `cvg _` while `cvg` is for `lim _`, but I think we can make an exception for preconditions, since `lim` is not a proposition, there is no ambiguity.
