### ISSUE TITLE
Forms library?

### ISSUE THREAD

**Issue by amahboubi** [math-comp/analysis#46]
Where is the 'forms' library imported by derive in the diff branch?

https://github.com/math-comp/analysis/blob/6b36593f4a6a612212163b25c6bad3522c7fa679/derive.v#L4

**Comment by amahboubi** [comment]
Ha, I guess the answer is commit 7b3288860c8d81c98b37dee80b94d4669635be33, hence it is in the algebra packages of the 'forms' branch of mathcomp...

In my opinion it is not very convenient to rely on a such a branch...

**Comment by CohenCyril** [comment]
Yes I agree, I found no better solution though :(. Do you have any idea?

**Comment by amahboubi** [comment]
Not sure it is the best place to ask but what is the status of the forms branch in mathcomp? It seems the last commit was on September 2016, and the only difference is the "forms" file. Is this case?

**Comment by CohenCyril** [comment]
This branch has been created in the few last week even though the commit pre-dates it by far (it is a squash of commits from the repo CohenCyril/spectral). The reason is that we have started reworking on it with Laurence and plan a PR in mathcomp. One application is to substitute the ad-hoc dot product theory of cfdot in classfun by the general theory of hermitian forms that forms should bring.

**Comment by amahboubi** [comment]
So in order to prepare a PR for math-comp you created a branch of math-comp?

**Comment by amahboubi** [comment]
Re-asking @CohenCyril,  apart from the diff branch of analysis, is there any other library you are aware of which depends on this math-comp/forms branch?

**Comment by CohenCyril** [comment]
Yes, I was recently convinced by some best practice manual, which explains that people with commit rights should prepare their pull requests in a specific branch of a repository rather than in a separate repo.
The master branch being the "official" one, the other may be development branches.

**Comment by CohenCyril** [comment]
> Re-asking @CohenCyril, apart from the diff branch of analysis, is there any other library you are aware of which depends on this math-comp/forms branch?

No, not that I am aware of (and I'm pretty sure I would be aware of it if it existed)

**Comment by amahboubi** [comment]
Naive question then: why not having forms being part of analysis during this transitional period?

**Comment by CohenCyril** [comment]
Why not, since the branch `diff` has not been merged in `master` yet, no "hard" decision has been taken yet.

**Comment by amahboubi** [comment]
I am not experience enough to have an opinion about the best practice you suggest, but in any case, I think that in this case, it was a debatable choice: as far as I can see, so far the branch just adds a file to algebra (btw it is a few commits behind master, any serious reason why?), for the purpose of making it available to analysis.

**Comment by amahboubi** [comment]
So a possible workflow could be: add forms.v, in its current state, to analysis,  to make it self-contained, create a branch  to math-comp and work there with @LaurenceRideau, possibly also create a branch in analysis to benchmark synchronization with the mathcomp branch. And one day merge the PR in mathcomp and update analysis's master. What do you think?

**Comment by CohenCyril** [comment]
> I am not experience enough to have an opinion about the best practice you suggest, but in any case, I think that in this case, it was a debatable choice: as far as I can see, so far the branch just adds a file to algebra 

Actually it also adds `spectral.v` ... but that's not the point. I guess I should rename the branch `experiments/forms` instead. As it has been done before

> (btw it is a few commits behind master, any serious reason why?),

Yes, this is because master changed since I created the branch, this is the natural evolution of any branch and it has to be rebased now and then...

> for the purpose of making it available to analysis.

No, that is not the point. The development of `forms` was totally independent from analysis and @LaurenceRideau and I planned to integrate it to mathcomp way before analysis was even created...


> So a possible workflow could be: add forms.v, in its current state, to analysis, to make it self-contained, create a branch to math-comp and work there with @LaurenceRideau, possibly also create a branch in analysis to benchmark synchronization with the mathcomp branch. And one day merge the PR in mathcomp and update analysis's master. What do you think?

That is an option. However I was afraid of having two unsynchronized copy of the same file, that is a really bad practice. But maybe we can make an exception and take your approach in this case.

**Comment by amahboubi** [comment]
Sure, I agree it is a bad practice, but I think that we are not exactly in this situation.
Ok, anyway we discussed this in person outside github and it seems that we now agree on the solution (having a copy of forms.v in this diff branch of analysis). I will close the issue as soon as it is done.

**Comment by drouhling** [comment]
I'll take care of this when I clean up the branch for a PR.
Before this, I want to finish re-doing my proof of LaSalle's Invariance Principle in the context of the diff branch because I might need a few additions.

**Comment by CohenCyril** [comment]
@drouhling I think it would be good enough to first submit a PR for everything you already did (including the local copy of form as asked by @amahboubi) and to do a second PR for the addition that you gather from LaSalle. Do you think you can do it?

**Comment by drouhling** [comment]
In fact I just finished the proof so the PR is the next step.
