### ISSUE TITLE
Wish a wishlist in the Wiki

### ISSUE THREAD

**Issue by t6s** [math-comp/analysis#498]
It would be nice to have a wishlist section in the wiki, where people can put in theorems / lemmas / definitions they want.

For example, looking at the pull-request #438 , I soon came up with the fact that every metric space is T4.
This sort of thing is too tiny to be filed as an issue, but not too trivial to be forgotten, and to be put somewhere.

**Comment by affeldt-aist** [comment]
We have added a `kind: wish` label in order to label issues that correspond to a request for a specific mathematical result. If you agree that this can fulfill the role of a wish list, we can maybe close this issue. What do you think?

**Comment by affeldt-aist** [comment]
@t6s Don't you want record your feature request as a wish issue?

**Comment by t6s** [comment]
> @t6s Don't you want record your feature request as a wish issue?

I will, thanks!
