### ISSUE TITLE
Address comment about classical quantifiers in boolp.v

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#515]
https://github.com/math-comp/analysis/blob/abf1b1c3d8e1f257df221e585dafd77fa3f698f6/theories/boolp.v#L696-L770

Should we uncomment and use?

**Comment by CohenCyril** [comment]
It is rather redundant with `asbool`; that's why it was actually staged for deletion... 
In which context would you like to use this?

**Comment by affeldt-aist** [comment]
I have no application in mind.
I just remembered this comment when looking at the automatically generated documentation
in which it appears as a big disgracious blue block of text.
It is maybe time to delete it.

**Comment by CohenCyril** [comment]
Yes, and with git it's not like it will be lost for good.

**Comment by CohenCyril** [comment]
(I changed the title of this PR for better archiving)
