### ISSUE TITLE
ordering of ereal_scope/ereal_dual_scope

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#518]
https://github.com/math-comp/analysis/blob/abf1b1c3d8e1f257df221e585dafd77fa3f698f6/theories/ereal.v#L116-L117

We may want to display ereal_scope declarations first since they are a bit shorter.

**Comment by CohenCyril** [comment]
I do not understand the comment. What is the proposed fix?

**Comment by proux01** [comment]
Parsing will be fine, but for printing, the following example
```Coq
From mathcomp Require Import all_algebra.
Require Import ereal.

Section Test1.

Variable R : numDomainType.
Variables x y : \bar R.

Check lte x y.
```
will print `(x < y)%dE` instead of `(x < y)%E` if we swap the `Notation` lines (same term in both notations, last one wins).
So I'd rather advocate in favor of keeping things like they are and closing this issue.

**Comment by affeldt-aist** [comment]
Indeed. Maybe it is worth putting a memo in the source file.

**Comment by proux01** [comment]
Indeed, here it is: #530
