### ISSUE TITLE
Please create a tag for Coq 8.15 in Coq Platform 2022.02

### ISSUE THREAD

**Issue by MSoegtropIMC** [math-comp/analysis#519]
The Coq team released Coq 8.15.0 on January 13, 2022.
The corresponding Coq Platform release 2022.02 should be released before February 28, 2022.
It can be delayed in case of difficulties until April 11, 2022, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knoweldege the latest released version of your project (0.3.12) does not work with Coq 8.15.0.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI appears to test this project, but has some special handling for your project which makes it difficult to retrieve the commit it tests for your project.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.15, preferably before February 14, 2022?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before January 25, 2022, it will be included in an early Coq Platform beta release of the for Coq 8.15.0.

The working branch of Coq Platform, which already supports Coq version 8.15.0, can be found here https://github.com/coq/platform/tree/main.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/193

**Comment by CohenCyril** [comment]
@MSoegtropIMC thanks for notifying us, we will investigate

**Comment by CohenCyril** [comment]
The last version of master should be fixed now, you can expect a release before February 14th.

**Comment by MSoegtropIMC** [comment]
@CohenCyril : I will do a 8.15 preview release tomorrow. Shall I put in a temporary opam package pointing to the current commit in master, or should I leave it away in the preview (not at all an issue for a preview).

**Comment by affeldt-aist** [comment]
> Could you please create a tag and opam package, or communicate us any existing tag that works with
> Coq branch v8.15, preferably before February 14, 2022?

The version 0.3.13 has been released with the accompanying opam packages.

**Comment by MSoegtropIMC** [comment]
Thanks! I updated Coq Platform and close this issue.

**Comment by affeldt-aist** [comment]
do we have at least one day to release 0.4.1?

**Comment by MSoegtropIMC** [comment]
Yes, sure. As far as I can tell Coq 8.15.1 is also not tagged yet. Also there are a few issues I wanted to fix.

Btw.: please feel free to reopen this kind of tracker issue any time in case you are working on a new version, so that I know and we can negotiate.

**Comment by MSoegtropIMC** [comment]
@affeldt-aist : I saw your 0.5 release - can you please confirm here that this is what should go into Coq Platform 2022.03?

**Comment by MSoegtropIMC** [comment]
Thanks for the confirmation! I did the update and will close this issue now.
