### ISSUE TITLE
Drop support for mathcomp < 1.13

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#538]
@math-comp/analysis

_Originally posted by @CohenCyril in https://github.com/math-comp/analysis/issues/334#issuecomment-1031473907_
>> These lemmas have been integrated to MathComp 1.13 and Analysis seems to depend on math-comp 1.13, but I can't find them within sequence.v in this branch, any idea why ?

>Hi! mathcomp-analysis is compatible with both (and with 1.14 too), and the default nix-shell uses the most conservative of the two (so 1.12.0).
>I am strongly in support of dropping 1.12.0 ASAP, that would solve your issue and several of mine :)

**Comment by proux01** [comment]
You mean "drop support for mathcomp < 1.13"? (just to be sure I understand, I'm perfectly OK with that)

**Comment by CohenCyril** [comment]
> You mean "drop support for mathcomp < 1.13"? (just to be sure I understand, I'm perfectly OK with that)

ahah, thanks! fixed

**Comment by affeldt-aist** [comment]
The support for mathcomp 1.12 has been dropped in master.
