### ISSUE TITLE
naming of measurable lemmas

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#566]
This one is called [`bigsetU_measurable`](
https://github.com/math-comp/analysis/blob/master/theories/measure.v#L684-L686)
while this one is called [`measurable_bigcup`](
https://github.com/math-comp/analysis/blob/master/theories/measure.v#L653-L654).
Should the former follow the naming of the latter?

**Comment by CohenCyril** [comment]
- [`bigsetU_measurable`](https://github.com/math-comp/analysis/blob/master/theories/measure.v#L684-L686) is the good name for this lemma.
- [`measurable_bigcup`](https://github.com/math-comp/analysis/blob/master/theories/measure.v#L653-L654) is **not a lemma**, it's a field of a factory, it will never be used outside of a builder section. However, for consitency and in anticipation of potential named based future features of HB, it could and should be renamed to the former.
