### ISSUE TITLE
naming in ereal.v

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#597]
https://github.com/math-comp/analysis/blob/8b15a9548996bffc32d5bb96a1b6fd91cbbc5f66/theories/ereal.v#L769-L772

wouldn't `addpinftye` and `addepinfty` bet better names?

**Comment by proux01** [comment]
Maybe `add_pinfty_e` and `adde_pinfty` but that's much longer. I don't know what's best.

**Comment by affeldt-aist** [comment]
I am not sure either. Are we sure we want to sick to `infty` for "infinity"? `oo` is much shorter...

**Comment by proux01** [comment]
I also like the conciseness of `oo`. I added that point to the topics for next meeting.
