### ISSUE TITLE
[Feature wish] metric space is T4

### ISSUE THREAD

**Issue by t6s** [math-comp/analysis#607]
It would be nice to have many exercise-level facts proved in the library, which would support the consistency of our formalization.
An example is that every metric space is T4 (or "normal").

A proofwiki entry is available: https://proofwiki.org/wiki/Metric_Space_is_T4

(I cannot add [kind: wish] label to this issue. Perhaps because of the lack of permission?)

**Comment by affeldt-aist** [comment]
> (I cannot add [kind: wish] label to this issue. Perhaps because of the lack of permission?)

There is maybe something to configure on github's side. I couldn't figure it out easily.

**Comment by affeldt-aist** [comment]
Since normal spaces have made their way into master we can maybe close this issues ? 
https://github.com/math-comp/analysis/blob/master/theories/topology.v#L427

**Comment by t6s** [comment]
Yes.
