### ISSUE TITLE
Reserved Notations should come first.

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#61]
https://github.com/math-comp/analysis/blob/061ff771d4d6421f8bca3df9cde8f2d9659e23e8/landau.v#L160

Reserved Notations should be after Require Imports and headers but before the first definition.

**Comment by affeldt-aist** [comment]
The only such Reserved Notation that is left now is about a notation for norm in hierarchy.v for which a dedicated issue (issue #110) has been opened. Close this issue?
