### ISSUE TITLE
Put littleo_linear0 in 0

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#67]
https://github.com/math-comp/analysis/blob/b6aa8eb636dee230ecb29b836fa8ff1eca55a513/derive.v#L320

As it is, this theorem is seldom rewritable from left to right, I'd rather have this theorem with `x = 0` and provide lemmas to bring any `o_x` to `o_0` instead.

**Comment by affeldt-aist** [comment]
I split little0_linear0 into three lemmas in branch issue67 so that the new little_linear0 is specialized to 0. The total number of lines of code is unchanged.

**Comment by affeldt-aist** [comment]
This is was the topic of PR #69 , which has been merged a long time ago. Maybe there was a reason for keeping this issue open but I do not remember/see it. Can we close? @CohenCyril
