### ISSUE TITLE
Remove this lemma about derivative and replace.

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#7]
https://github.com/math-comp/analysis/blob/e2d3d4c57f3c0797d06891669c336ba587eb2ae5/derive.v#L135

`'d_a f x / x` although valid is a non canonical way for getting the coefficient of a linear map (no need to take a limit by the way, it is supposed to be constant). The canonical way is to first take the Jacobian (using lin1_mx) and in dimension 1 (since R^o is), just take the only coefficient: jacobian f 0 0.

`derivative1 f a = 'J_a f 0 0`

**Comment by affeldt-aist** [comment]
The desired lemma has been renamed derivemxE in the meantime and depends on deriveE that now has a tentative proof.
