### ISSUE TITLE
Linear and littleo of id is zero.

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#70]
https://github.com/math-comp/analysis/blob/aaaad64e8854a2207f51c6a216d5bad87b6210d5/derive.v#L337

I am afraid this is difficult to use too... Maybe `f =o id -> f = cst 0` is better?

**Comment by affeldt-aist** [comment]
Indeed. At least, it was easier to use in the proof of diff_unique. In branch issue70:
* New statement: https://github.com/math-comp/analysis/blob/3c7cab8956cff219fbebf7a4a7bcb9506baf2b7f/derive.v#L319
* Where it is used: https://github.com/math-comp/analysis/blob/3c7cab8956cff219fbebf7a4a7bcb9506baf2b7f/derive.v#L344

**Comment by CohenCyril** [comment]
closed by 016979767c8291111dfdf49e2a6501198e6fdac1
