### ISSUE TITLE
Not sure why this lemma is exported

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#71]
https://github.com/math-comp/analysis/blob/aaaad64e8854a2207f51c6a216d5bad87b6210d5/derive.v#L318
Shouldn't it be a part of `littleo_linear0`?

**Comment by affeldt-aist** [comment]
Indeed, there is no point in keeping it outside. The proof of littleo_linear0 is now short enough for it to blend smoothly. Deleted with the PR corresponding to issue #70.

**Comment by CohenCyril** [comment]
closed by 016979767c8291111dfdf49e2a6501198e6fdac1
