### ISSUE TITLE
Looks subsumed by `littleo_center0`

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/analysis#72]
https://github.com/math-comp/analysis/blob/aaaad64e8854a2207f51c6a216d5bad87b6210d5/derive.v#L346

**Comment by affeldt-aist** [comment]
Yes, it can be recovered easily. Deleted with the PR for issue #70.

**Comment by CohenCyril** [comment]
closed by 016979767c8291111dfdf49e2a6501198e6fdac1
