### ISSUE TITLE
Relation composition

### ISSUE THREAD

**Issue by zstone1** [math-comp/analysis#759]
The `\o` and `^-1` operation used in entourages are instances of a much more general "relation composition". We should add this notion to classical_sets, build its theory. There are several results from `topology.v` should be moved there.

**Comment by affeldt-aist** [comment]
NB: `\o` has been moved (as `\;`) to `classical_sets.v` as well as a couple of lemmas

**Comment by affeldt-aist** [comment]
Note that as of 2024-09-19, notations for composition and inverse for relations have been moved to `classical_sets.v` with a dedicate scope `relation_scope`

**Comment by affeldt-aist** [comment]
It was decided to close this issue during the meeting of [2024-10-10]: now that the notation has landed in a proper place, the theory will build up naturally.
