### ISSUE TITLE
release/update classical&analysis for mathcomp 1.16

### ISSUE THREAD

**Issue by clayrat** [math-comp/analysis#842]
Currently both https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-classical/coq-mathcomp-classical.0.6.0/opam and https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-analysis/coq-mathcomp-analysis.0.6.0/opam conflict with 1.16

**Comment by proux01** [comment]
@clayrat OPAM packages updated: https://github.com/coq/opam-coq-archive/pull/2467

**Comment by affeldt-aist** [comment]
Thanks @proux01 !
