### ISSUE TITLE
naming of `measurable_fun` lemmas

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#916]
The naming of lemmas about measurable functions of type `T -> \bar R` is not completely homogeneous, e.g., `emeasurable_fun_min` vs. `measurable_fun_abse`.
The second example looks better because `measurable_fun` and `abse` make sense taken individually.
(So `emeasurable_fun_min` should at least be fixed.)
Question: or is `measurable_fune_abs` better?

I am asking because, on the other hand, `emeasurable_fun` is used in lemmas such as `emeasurable_fun_c_infty` where `measurable_fun` about an extended real number-valued function appears as an hypothesis. In this case, it seems to me that we should rather use `measurable_fune_c_infty` on the model of `cvgr/cvge` lemmas. Hence the question above.

I am asking some input before working on a PR because it might take some time.

@CohenCyril @proux01

**Comment by proux01** [comment]
It seems the rule is to put the e\r as soon as possible so `measurable_fune_*` looks like the most uniform solution.

**Comment by affeldt-aist** [comment]
In any case, `emeasurable_fun` is not good,  and I need to make sure whether `measurable_fune/r_*` can be of interest to disambiguate when using more systematically the approach `measurable_fun + identifier`. As for the shortening, I guess this is better to test it as a second phase to avoid premature clashes. Thanks!
