### ISSUE TITLE
naming of `integralM`

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#938]
https://github.com/math-comp/analysis/blob/46f7a6cfe7c1c2d421c7a1f756fb8b179a5ae0a2/theories/lebesgue_integral.v#L2026-L2027

shouldn't this be named `integral_distrr` on the model of `big_distrr`?

**Comment by CohenCyril** [comment]
`big_distrr` does not presume the operators at play and is about distributivity, here they are defined and this is not distributivity (addition/integral does not distributes over multiplication) but (nonnegative) scalability. However just `M` suggest we are taking the product of two functions. Hence I would go for `Z` or `Zl` instead

**Comment by affeldt-aist** [comment]
or maybe `rM` and `Mr` ?
