### ISSUE TITLE
`bigcup_bigcup` naming

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#988]
https://github.com/math-comp/analysis/blob/7da865547861fd6937802e1f6e99f3c6d7f4b7b6/classical/classical_sets.v#L1797-L1799

Wouldn't it better to call this `bigcup_bigcup_setM` to keep `bigcup_bigcup` for the nesting of `bigcup` as in
```
Lemma bigcup_bigcup (I : Type) T1 T2 (F : I -> set T1) (G : T1 -> set T2) :
  \bigcup_(i in \bigcup_n F n) G i = \bigcup_n \bigcup_(i in F n) G i.
```

**Comment by CohenCyril** [comment]
Indeed, and we could rather have
```coq
Lemma bigcup_setM {J : Type} (F : I -> J -> set T) (P : set I) (Q : set J) : 
   \bigcup_(k in P `*` Q) F k.1 k.2 =    \bigcup_(i in P) \bigcup_(j in Q) F i j.
```
instead.
